export const reducerTypes={
    LOAD_POSTS:"LOAD_POST_DATA",
    LOAD_USERDATA:"LOAD_USER_DATA",
    ADD_POST:"ADD_POST",
    USERS_POSTLIST:"USERS_POSTLIST",
    DELETE_POST: "DELETE_POST",
    EDIT_POST:"EDIT_POST",
    LOAD_BOOKMARKS:"LOAD_BOOKMARKS_DATA",
    ADD_TO_BOOKMARK:"ADD_POST_TO_BOOKMARK",
    REMOVE_FROM_BOOKMARK:"REMOVE_FROM_BOOKMARK",
    LIKED_POST:"LIKED_POST",
    DISLIKED_POST:"REMOVED_FROM_LIKED_POST"
}