export const reducerTypes={
    LOAD_POSTS:"LOAD_POST_DATA",
    LOAD_USERDATA:"LOAD_USER_DATA",
    ADD_POST:"ADD_POST",
    USERS_POSTLIST:"USERS_POSTLIST",
    DELETE_POST: "DELETE_POST",
    EDIT_POST:"EDIT_POST",
}